config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'

  constraints ->(request) { request.session[:user_id].present? } do
    # ログインしてる時のパス
    root to: 'news#index'
  end
  # ログインしてない時のパス
  root 'static_pages#home'

  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  post '/testlogin', to: 'sessions#testlogin'
  resources :users
  resources :news
  resources :keywords
  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
<div class="clear">
</div>
<footer class="footer">
  <small>© 2019. All Rights Reserved.</small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
    <%= link_to "News Crawler", root_path, id: "logo" %>
        <nav>
            <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "ヘルプ", help_path %></li>
            <% if logged_in? %>
                <li><%= link_to "キーワード", keywords_path %></li>
                <li><%= link_to "ニュース", news_index_path %></li>
                <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= current_user.name %>
                <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                    <li><%= link_to "プロフィール", current_user %></li>
                    <li><%= link_to "設定", edit_user_path(current_user) %></li>
                    <li class="divider"></li>
                    <li>
                    <%= link_to "ログアウト", logout_path, method: :delete %>
                    </li>
                </ul>
                </li>
            <% else %>
                <li><%= link_to "ログイン", login_path %></li>
            <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | News Crawler</title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
    <% end %>
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>
  <%= debug(params) if Rails.env.development? %>
  </body>
</html>